add proxy monitor config
mozilla-extensions/xpi-manifest pull request #130
Opened 2021-09-04 20:24 UTC by mixedpuppy

Other config files are here https://github.com/mozilla-extensions/proxy-monitor/pull/6

2021-09-07 15:19 UTC, escapewindow requested changes
It looks like we need to add `proxymonitor` to taskcluster/ci/config.yml.

2021-09-07 17:53 UTC, mixedpuppy commented
> It looks like we need to add `proxymonitor` to taskcluster/ci/config.yml.

bah, forgot to git add that file.

2021-09-07 18:19 UTC, escapewindow requested changes

2021-09-07 18:19 UTC, escapewindow commented on taskcluster/ci/config.yml
> +            default-repository: https://github.com/mozilla-extensions/proxy-monitor
This looks like a private repo, so we'll need `git@` URL formatting or the task will hang trying to clone.

2021-09-08 16:18 UTC, escapewindow commented on taskcluster/ci/config.yml
> +            default-repository: https://github.com/mozilla-extensions/proxy-monitor
```suggestion
            default-repository: git@github.com:mozilla-extensions/proxy-monitor
```

2021-09-08 16:28 UTC, escapewindow commented on manifests/proxy-monitor.yml
> +install-type: npm
```suggestion
install-type: npm
docker-image: node-lts-latest
```

2021-09-08 16:36 UTC, escapewindow approved these changes
Just needed 2 lines of changes, plus a merge of master.

2021-09-08 16:36 UTC, merged