Set up search-engine-usage-study Rally extension
mozilla-extensions/xpi-manifest pull request #140
Opened 2022-01-03 23:26 UTC by rhelmer

2022-01-03 23:59 UTC, escapewindow requested changes

2022-01-03 23:59 UTC, escapewindow commented on taskcluster/ci/config.yml
> +            default-repository: https://github.com/mozilla-rally/search-engine-usage-study
This will need to be `git@github.com:mozilla-rally-search-engine-usage-study` for the private repo or the build will hang.

2022-01-04 16:49 UTC, escapewindow commented
```
[vcs 2022-01-04T16:17:33.670Z] executing ['git', 'clone', 'git@github.com:mozilla-rally-search-engine-usage-study', '/builds/worker/checkouts/src']
[vcs 2022-01-04T16:17:33.673Z] Cloning into '/builds/worker/checkouts/src'...
[vcs 2022-01-04T16:17:33.692Z] Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
[vcs 2022-01-04T16:17:33.850Z] ERROR: Repository not found.
[vcs 2022-01-04T16:17:33.850Z] fatal: Could not read from remote repository.
[vcs 2022-01-04T16:17:33.850Z] 
[vcs 2022-01-04T16:17:33.850Z] Please make sure you have the correct access rights
[vcs 2022-01-04T16:17:33.850Z] and the repository exists
```

Did you follow https://github.com/mozilla-extensions/xpi-manifest/blob/master/docs/adding-a-new-xpi.md#external-repos ?

2022-01-04 17:13 UTC, rhelmer commented
> ```
> [vcs 2022-01-04T16:17:33.670Z] executing ['git', 'clone', 'git@github.com:mozilla-rally-search-engine-usage-study', '/builds/worker/checkouts/src']
> [vcs 2022-01-04T16:17:33.673Z] Cloning into '/builds/worker/checkouts/src'...
> [vcs 2022-01-04T16:17:33.692Z] Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
> [vcs 2022-01-04T16:17:33.850Z] ERROR: Repository not found.
> [vcs 2022-01-04T16:17:33.850Z] fatal: Could not read from remote repository.
> [vcs 2022-01-04T16:17:33.850Z] 
> [vcs 2022-01-04T16:17:33.850Z] Please make sure you have the correct access rights
> [vcs 2022-01-04T16:17:33.850Z] and the repository exists
> ```
> 
> Did you follow https://github.com/mozilla-extensions/xpi-manifest/blob/master/docs/adding-a-new-xpi.md#external-repos ?

Oh, I actually moved it to `mozilla-extensions` org, hopefully that makes it easier.

2022-01-04 18:25 UTC, escapewindow approved these changes

2022-01-04 18:25 UTC, merged