Add addons-linter kind as a prerequisite of release-signing kind
mozilla-extensions/xpi-manifest pull request #170
Opened 2022-05-20 12:42 UTC by willdurand

Fixes https://github.com/mozilla-extensions/xpi-manifest/issues/169 (maybe)

---

The `group-by` didn't work as expected (see: https://github.com/mozilla-extensions/xpi-manifest/issues/169#issuecomment-1132830502) so I tried to not have a `group-by` essentially and at least the graph was loaded by `taskgraph`.
I also fixed errors in the existing code since I actually triggered these error handling blocks.

That being said, I wasn't able to review the actual graph for `release-signing` with `taskgraph`. I tried to supply a few parameters but that didn't change anything so I am not too sure if that's going to work :/

2022-05-23 15:41 UTC, escapewindow requested changes
This removes the release-signing task from promote graphs.
We probably need group-by xpi-name functionality.

2022-05-23 15:46 UTC, willdurand commented
> This removes the release-signing task from promote graphs.

Is this why I cannot see them with the `taskgraph` command?

2022-05-23 16:11 UTC, willdurand commented
Ok that looks a bit better, at least `taskgraph` shows me some output...

2022-05-23 21:16 UTC, escapewindow requested changes
Next problem: duplicate release-signing tasks:

```
Traceback (most recent call last):
  File "/Users/asasaki/src/tc/taskgraph/src/taskgraph/main.py", line 742, in main
    args.command(vars(args))
  File "/Users/asasaki/src/tc/taskgraph/src/taskgraph/main.py", line 409, in show_taskgraph
    generate_taskgraph(options, parameters, logdir)
  File "/Users/asasaki/src/tc/taskgraph/src/taskgraph/main.py", line 188, in generate_taskgraph
    out = format_taskgraph(options, spec, logfile(spec))
  File "/Users/asasaki/src/tc/taskgraph/src/taskgraph/main.py", line 144, in format_taskgraph
    tg = getattr(tgg, options["graph_attr"])
  File "/Users/asasaki/src/tc/taskgraph/src/taskgraph/generator.py", line 188, in target_task_graph
    return self._run_until("target_task_graph")
  File "/Users/asasaki/src/tc/taskgraph/src/taskgraph/generator.py", line 412, in _run_until
    k, v = next(self._run)
  File "/Users/asasaki/src/tc/taskgraph/src/taskgraph/generator.py", line 320, in _run
    raise Exception("duplicate tasks with label " + task.label)
Exception: duplicate tasks with label release-signing-rally-core-addon
```

I have some test parameters files in #171 , also in https://hg.mozilla.org/build/braindump/file/tip/taskcluster/taskgraph-diff/params-xpi . We can replicate this error message by

`taskgraph target-graph -p path/to/privileged-promote.yml`

The above command is broken on your branch, and fine on `main`. We may want to add some breakpoints via

```
import pdb
pdb.set_trace()
```

at various places in the code to figure out what's going on.

(Once you get past the error, you can see diffs via

```
# Single graph, see what task labels are added or removed
taskgraph target-graph --diff main -p path/to/privileged-promote.yml
# Single graph, see the entire task definitions
taskgraph target-graph --diff main -p path/to/privileged-promote.yml -J
# Multiple graphs, see what task labels are added or removed
taskgraph target-graph --diff main -p path/to/params/
# Multiple graphs, see the entire task definitions
taskgraph target-graph --diff main -p path/to/params/ -J
```

2022-05-24 07:36 UTC, willdurand commented
> `taskgraph target-graph -p path/to/privileged-promote.yml`

Thanks, I didn't know about this yaml file. I am not sure where it actually is located but I'll find out.

2022-05-24 11:22 UTC, willdurand commented
All graphs seem to load fine now and all diffs I've reviewed locally make sense.

Specifically, the `full` graph loads and shows that _firefox-translations_ seems fixed (although probably not related to this patch but to #172):

```diff
     "payload": {
       "command": [
         "/usr/local/bin/run-task",
         "--firefoxtranslations-checkout=/builds/worker/checkouts/vcs",
         "--task-cwd",
         "/builds/worker/checkouts/vcs",
         "--fetch-hgfingerprint",
         "--",
         "bash",
         "-cx",
-          "curl -sSL --fail --retry 3 -o firefox-translations.xpi \"$XPI_URL\" && npx -y addons-linter@5.4.0 --privileged --boring --disable-xpi-autoclose --max-manifest-version=2 firefox-translations.xpi"
+          "curl -sSL --fail --retry 3 -o firefox_translations.xpi \"$XPI_URL\" && npx -y addons-linter@5.4.0 --privileged --boring --disable-xpi-autoclose --max-manifest-version=2 firefox_translations.xpi"
       ],
```

I also ran `taskgraph target-graph -p taskcluster/test/params/privileged-promote.yml -J --diff main`:

```diff
--- target_task_graph@073fe43f7004
+++ target_task_graph@dep-linter
@@ -45,60 +45,60 @@
         },
         "parent": "",
         "xpi-name": "rally-core-addon"
       },
       "metadata": {
         "description": "Run addons-linter",
         "name": "addons-linter-rally-core-addon",
         "owner": "ahal@pm.me",
         "source": "https://github.com/mozilla-extensions/xpi-manifest/blob/b336cf05374ebfb43b0142433c46a93ac9d9616f/taskcluster/ci/addons-linter"
       },
       "payload": {
         "command": [
           "/usr/local/bin/run-task",
           "--rallycoreaddon-checkout=/builds/worker/checkouts/vcs",
           "--task-cwd",
           "/builds/worker/checkouts/vcs",
           "--fetch-hgfingerprint",
           "--",
           "bash",
           "-cx",
-          "curl -sSL --fail --retry 3 -o rally-core-addon.xpi \"$XPI_URL\" && npx -y addons-linter@5.4.0 --privileged --boring --disable-xpi-autoclose --max-manifest-version=2 rally-core-addon.xpi"
+          "curl -sSL --fail --retry 3 -o rally_core.xpi \"$XPI_URL\" && npx -y addons-linter@5.4.0 --privileged --boring --disable-xpi-autoclose --max-manifest-version=2 rally_core.xpi"
         ],
         "env": {
           "ARTIFACT_PREFIX": "public/build",
           "HG_STORE_PATH": "/builds/worker/checkouts/hg-store",
           "MOZ_AUTOMATION": "1",
           "MOZ_SCM_LEVEL": "3",
           "RALLYCOREADDON_BASE_REPOSITORY": "https://github.com/mozilla-rally/rally-core-addon",
           "RALLYCOREADDON_HEAD_REF": "release",
           "RALLYCOREADDON_HEAD_REPOSITORY": "https://github.com/mozilla-rally/rally-core-addon",
           "RALLYCOREADDON_HEAD_REV": "ff05b95fa1e953cc20f048f4b92e519aa542351d",
           "RALLYCOREADDON_REPOSITORY_TYPE": "git",
           "REPOSITORIES": "{\"rallycoreaddon\": \"Rally Core Add-on\"}",
           "REPO_PREFIX": "rallycoreaddon",
           "SCCACHE_DISABLE": "1",
           "TASKCLUSTER_VOLUMES": "/builds/worker/.cache;/builds/worker/checkouts",
           "VCS_PATH": "/builds/worker/checkouts/vcs",
           "XPI_INSTALL_TYPE": "npm",
           "XPI_URL": {
-            "artifact-reference": "<build/public/build/rally-core-addon.xpi>"
+            "artifact-reference": "<build/public/build/rally_core.xpi>"
           }
         },
         "features": {
           "taskclusterProxy": true
         },
         "image": {
           "path": "public/image.tar.zst",
           "taskId": {
             "task-reference": "<docker-image>"
           },
           "type": "task-image"
         },
         "maxRunTime": 7200,
         "onExitStatus": {
           "purgeCaches": [
             72
           ],
           "retry": [
             72
           ]
@@ -808,40 +808,41 @@
       "addon-type": "privileged",
       "always_target": false,
       "code-review": true,
       "kind": "release-signing",
       "resources": [
         "/Users/william/projects/mozilla/xpi-manifest/manifests/rally-core-addon.yml"
       ],
       "run_on_projects": [
         "all"
       ],
       "run_on_tasks_for": [
         "action"
       ],
       "shipping-phase": "promote",
       "signed": true,
       "xpis": {
         "web-ext-artifacts/rally_core.xpi": "public/build/rally_core.xpi"
       }
     },
     "dependencies": {
+      "addons-linter": "addons-linter-rally-core-addon",
       "build": "build-rally-core-addon"
     },
     "description": "Release-sign XPI",
     "if_dependencies": [],
     "kind": "release-signing",
     "label": "release-signing-rally-core-addon",
     "optimization": null,
     "soft_dependencies": [],
     "task": {
       "created": {
         "relative-datestamp": "0 seconds"
       },
       "deadline": {
         "relative-datestamp": "1 day"
       },
       "expires": {
         "relative-datestamp": "1 year"
       },
       "extra": {
         "artifact_prefix": "public/build",
```

2022-05-24 15:52 UTC, willdurand commented
(rebased)

2022-05-24 20:29 UTC, escapewindow approved these changes
Looks good, thank you!

2022-05-24 20:29 UTC, merged