search-engine-usage-study repo is now public
mozilla-extensions/xpi-manifest pull request #179
Opened 2022-08-08 21:46 UTC by rhelmer

2022-08-08 21:48 UTC, escapewindow requested changes
We also need to change https://github.com/mozilla-extensions/xpi-manifest/blob/main/taskcluster/ci/config.yml#L117 to be an https url rather than ssh.

2022-08-08 22:04 UTC, escapewindow commented on taskcluster/ci/config.yml
> +            default-repository: https://github.com/mozilla-rally/search-engine-usage-study.git
I think this needs to be `mozilla-extensions`

2022-08-08 22:22 UTC, escapewindow commented
Build is failing: circular deps, OOM, https://firefox-ci-tc.services.mozilla.com/tasks/dDf3tF4URreQh_Rra238fA/runs/0/logs/public/logs/live.log . Looks like it's failing in CI too.

2022-08-08 23:17 UTC, escapewindow commented
Aha, we have to uplift to the release branch before this PR will go green.

2022-08-09 16:12 UTC, rhelmer commented
> Aha, we have to uplift to the release branch before this PR will go green.

Makes sense! OK did so yesterday, let's see if it works now.

2022-08-09 16:24 UTC, escapewindow approved these changes

2022-08-09 16:24 UTC, merged