Rename the rally output file
mozilla-extensions/xpi-manifest pull request #95
Opened 2020-12-18 10:23 UTC by Dexterp37

This is a follow up to #92 and to the requested changes on mozilla-rally/core-addon#271

The artifact name was renamed, so we can now change it too. The new name will be picked up by the clone in `mozilla-extension` as soon as we cut a new release.

2020-12-18 10:23 UTC, Dexterp37 commented
cc @rhelmer

2020-12-18 17:05 UTC, escapewindow requested changes
We'll need a PR to rename in https://github.com/mozilla-extensions/rally-core-addon/blob/master/package.json before this will work. Other than that it looks good, thank you!

2020-12-18 17:08 UTC, Dexterp37 commented
> 
> 
> We'll need a PR to rename in https://github.com/mozilla-extensions/rally-core-addon/blob/master/package.json before this will work. Other than that it looks good, thank you!

We're renaming [in this PR](https://github.com/mozilla-rally/core-addon/pull/271). Once we cut a new release following [our process](https://github.com/mozilla-rally/core-addon/blob/master/docs/RELEASE_PROCESS.md), the updates will get to the `mozilla-extensions` repo.

@escapewindow does this PR need to block on us cutting a release? We're aware we won't be able to release anything until we update our clone repo.

2020-12-18 17:09 UTC, escapewindow commented
If we land this before the package is renamed, CI will be broken in this repo until it is renamed. Let's rename in both locations at approximately the same time.

2020-12-18 17:12 UTC, Dexterp37 commented
> 
> 
> If we land this before the package is renamed, CI will be broken in this repo until it is renamed. Let's rename in both locations at approximately the same time.

Oh, in the `xpi-template` will be broken? Cool, if so, let's wait a bit. I thought we'd only break our own repos.

2021-01-08 20:01 UTC, jmaher commented
this will need to be rebased upon: https://github.com/mozilla-extensions/xpi-manifest/blob/master/manifests/rally-core-addon.yml

2021-01-11 08:46 UTC, Dexterp37 commented
> 
> 
> this will need to be rebased upon: https://github.com/mozilla-extensions/xpi-manifest/blob/master/manifests/rally-core-addon.yml

Thanks, I'll take care of it.

2021-01-11 08:52 UTC, Dexterp37 commented
@escapewindow this is now ready for another look/merge. I'll be merging the change in the core-addon repo as soon as this gets merged!

2021-01-11 17:06 UTC, escapewindow commented
We need to merge https://github.com/mozilla-extensions/rally-core-addon/pull/12 before this can land.

2021-01-11 18:28 UTC, Dexterp37 commented
> 
> 
> We need to merge [mozilla-extensions/rally-core-addon#12](https://github.com/mozilla-extensions/rally-core-addon/pull/12) before this can land.

This was merged :)

2021-01-11 20:22 UTC, escapewindow approved these changes

2021-01-11 20:22 UTC, merged

2021-01-11 20:29 UTC, escapewindow commented
Green! https://firefox-ci-tc.services.mozilla.com/tasks/groups/Ov4d84s2QK2-mx3mKuOKYw